### ISSUE TITLE
Incorrect logic in REST-layer folder name validator

### ISSUE THREAD

**Issue by zachmullen** [girder/dkc-next#162]
[This `UniqueTogetherValidator`](https://github.com/girder/dkc-next/blob/78ddc26f628b53fd0fb7123270848aadbf5578bb/dkc/core/rest/folder.py#L60-L64) has incorrect logic. Namely, if a root folder exists with a given name, that name cannot be used for any other folder, regardless of whether it's a root or not.

Steps to reproduce:

1. Create  root folder named "foo".
2. Create a non-root folder anywhere else named "foo". 

* Expectation: operation succeeds.
* Actual result: HTTP 400 with error "A root folder with that name already exists."

**Comment by zachmullen** [comment]
@brianhelba I pushed [this branch](https://github.com/girder/dkc-next/tree/folder-name-unique-validator-bug) containing a failing test case (76106c3604a7b7be3ff5639982a891957414b5f3), feel free to take over that branch.

**Comment by brianhelba** [comment]
@zachmullen Working on this now.
