### ISSUE TITLE
Attach Sentry to SPA

### ISSUE THREAD

**Issue by mgrauer** [girder/dkc-next#87]
https://docs.sentry.io/platforms/javascript/guides/vue/
DSN: `https://4dcc2f6367fa4d3aa5be8936d1ac00da@o267860.ingest.sentry.io/5552307`

**Comment by brianhelba** [comment]
Updated the issue description with the DSN.

**Comment by zachmullen** [comment]
Resolved in https://github.com/girder/girder_web_components/commit/cf4673bfa1152e92324aedbff85ce4e778d61c60

**Comment by zachmullen** [comment]
And proof that it works: https://sentry.io/organizations/kitware-data/issues/2139819940/?project=5552307&query=is%3Aunresolved

That error should be resolved once #109  is merged.
